# Copyright (c) 2015 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

---

- get_url: url=https://s3.amazonaws.com/bosh-init-artifacts/bosh-init-{{ bosh_init_version }}-{{ ansible_system | lower }}-amd64
           dest=/usr/local/bin/bosh-init mode=a+x
  become: yes

- include_vars: "{{ ansible_distribution }}.yml"

- apt: name={{ item }} state=present
  with_items: bosh_init_pkgs
  become: yes
  when: ansible_distribution == 'Ubuntu'

- yum: name={{ item }} state=present
  with_items: bosh_init_pkgs
  become: yes
  when: ansible_distribution == 'CentOS'

# vi:et:sw=2 ts=2 sts=2 ft=ansible
